demo/demo-web/src/de/hinderkott/demo/HelloWorldCDIBean.java
package de.hinderkott.demo;

import java.io.Serializable;
import java.security.Principal;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import jakarta.annotation.PostConstruct;
import jakarta.ejb.EJB;
import jakarta.faces.view.ViewScoped;
import jakarta.inject.Named;

@Named
@ViewScoped
public class HelloWorldCDIBean implements Serializable {

	private static final long serialVersionUID = -6503517043368074756L;

	public static final Log log = LogFactory.getLog(HelloWorldCDIBean.class);

	@EJB
	HelloWorldServiceLocal service;

	Principal ejbPrincipal;

	@PostConstruct
	public void init() {
		ejbPrincipal = service.getPrincipal();
	}

	public String getText() {
		return ejbPrincipal.getName();
	}

}

demo/demo-web/WebContent/landing.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<title>Demo-Guest</title>
</h:head>

<h:body>
	<h:form >
		<h:commandButton value="login"  action="/ui/index?faces-redirect=true" />
	</h:form>
</h:body>

</html>

demo/demo-web/WebContent/ui/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>Demo</title>
</h:head>
<h:body>
	<h:outputText value="WEB: #{userSessionManager.getOIDCUser().getFullName()}"/><br/>
	<h:outputText value="EJB: #{helloWorldCDIBean.text}" />
</h:body>
</html>